name: Publish Staging Website

on:
  push:
    branches:
      - staging


jobs:
  web-deploy:
    name: ðŸš€ Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get Latest Code
      uses: actions/checkout@v3

    # Setup Node
    - name: ðŸŸ¢ Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    # Install dependencies
    - name: ðŸ“¦ Install JS Dependencies
      run: npm ci

    # Build assets
    - name: ðŸ›  Build JS Assets
      run: npm run build

    - name: ðŸ“‚ Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.DEMOS_FTP_HOST }}
        username: ${{ secrets.DEMOS_FTP_USER }}
        password: ${{ secrets.DEMOS_FTP_PASSWORD }}
        server-dir: public_html/wp-content/plugins/sample-wp-blocks/
